# Generated by Django 2.0.1 on 2018-01-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
                ('first_name', models.TextField(blank=True, db_column='First Name', null=True)),
                ('last_name', models.TextField(blank=True, db_column='Last Name', null=True)),
                ('company_name', models.TextField(blank=True, db_column='Company Name', null=True)),
                ('address_line_1', models.TextField(blank=True, db_column='Address Line 1', null=True)),
                ('address_line_2', models.TextField(blank=True, db_column='Address Line 2', null=True)),
                ('city', models.TextField(blank=True, db_column='City', null=True)),
                ('state', models.TextField(blank=True, db_column='State', null=True)),
                ('zip_code', models.TextField(blank=True, db_column='ZIP Code', null=True)),
                ('country', models.TextField(blank=True, db_column='Country', null=True)),
                ('home_phone', models.TextField(blank=True, db_column='Home Phone', null=True)),
                ('work_phone', models.TextField(blank=True, db_column='Work Phone', null=True)),
                ('last_advertised', models.TextField(blank=True, db_column='Last Advertised', null=True)),
                ('customer_type', models.TextField(blank=True, db_column='Customer Type', null=True)),
                ('ad_size', models.TextField(blank=True, db_column='Ad Size', null=True)),
                ('color', models.TextField(blank=True, db_column='Color', null=True)),
                ('placement', models.TextField(blank=True, db_column='Placement', null=True)),
                ('e_mail_address', models.TextField(blank=True, db_column='E-mail Address', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('renewaldate', models.TextField(blank=True, db_column='RenewalDate', null=True)),
                ('new_copy', models.TextField(blank=True, db_column='New Copy', null=True)),
                ('commission', models.TextField(blank=True, db_column='Commission', null=True)),
                ('price', models.TextField(blank=True, db_column='Price', null=True)),
                ('ad_page', models.TextField(blank=True, db_column='Ad Page', null=True)),
            ],
            options={
                'db_table': 'Advertisments',
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.TextField(blank=True, db_column='LNAME', null=True)),
                ('fname', models.TextField(blank=True, db_column='FNAME', null=True)),
                ('mrg', models.TextField(blank=True, db_column='MRG', null=True)),
                ('pobox', models.TextField(blank=True, db_column='POBOX', null=True)),
                ('addr', models.TextField(blank=True, db_column='ADDR', null=True)),
                ('city', models.TextField(blank=True, db_column='CITY', null=True)),
                ('state', models.TextField(blank=True, db_column='STATE', null=True)),
                ('zip', models.TextField(blank=True, db_column='ZIP', null=True)),
                ('hphone', models.TextField(blank=True, db_column='HPHONE', null=True)),
                ('wphone', models.TextField(blank=True, db_column='WPHONE', null=True)),
                ('email', models.TextField(blank=True, db_column='EMAIL', null=True)),
                ('function', models.TextField(blank=True, db_column='FUNCTION', null=True)),
                ('prem_sub_current_year', models.TextField(blank=True, db_column='Prem Sub current year', null=True)),
                ('prem_sub_last_year', models.TextField(blank=True, db_column='Prem Sub last year', null=True)),
                ('prem_level', models.TextField(blank=True, db_column='Prem level', null=True)),
                ('prod_invt', models.TextField(blank=True, db_column='Prod invt', null=True)),
                ('isbusnmember', models.TextField(blank=True, db_column='IsBusnMember', null=True)),
                ('busn_level', models.TextField(blank=True, db_column='Busn Level', null=True)),
                ('is_cvcc_seas_tix', models.TextField(blank=True, db_column='Is CVCC seas tix', null=True)),
                ('yta', models.TextField(blank=True, db_column='YTA', null=True)),
                ('fk_list', models.TextField(blank=True, db_column='FK LIST', null=True)),
                ('vac_extr', models.TextField(blank=True, db_column='VAC EXTR', null=True)),
                ('seller', models.TextField(blank=True, db_column='Seller', null=True)),
                ('board', models.TextField(blank=True, db_column='Board', null=True)),
                ('actor', models.TextField(blank=True, db_column='Actor', null=True)),
                ('guild', models.TextField(blank=True, db_column='Guild', null=True)),
                ('donor', models.TextField(blank=True, db_column='Donor', null=True)),
            ],
            options={
                'db_table': 'Mailing_List',
            },
        ),
        migrations.CreateModel(
            name='Producermasterdatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(blank=True, db_column='Company Name', null=True)),
                ('contact_person', models.TextField(blank=True, db_column='Contact Person', null=True)),
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
                ('has_produced_field', models.TextField(blank=True, db_column='has produced?', null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('city', models.TextField(blank=True, db_column='City', null=True)),
                ('state', models.TextField(blank=True, db_column='State', null=True)),
                ('zip', models.TextField(blank=True, db_column='Zip', null=True)),
                ('ph', models.TextField(blank=True, db_column='PH', null=True)),
                ('email', models.TextField(blank=True, db_column='Email', null=True)),
                ('number_2nd_contact_s_field', models.TextField(blank=True, db_column='2nd contact(s)', null=True)),
                ('physical_address', models.TextField(blank=True, db_column='Physical Address', null=True)),
                ('likely_options', models.TextField(blank=True, db_column='Likely Options', null=True)),
                ('fax', models.TextField(blank=True, db_column='Fax', null=True)),
            ],
            options={
                'db_table': 'ProducerMasterDatabase',
            },
        ),
    ]
